[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "api"

[[redirects]]
  from = "/api/action/:action"
  to = "/.netlify/functions/netlify_action?action=:action"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
